# https://github.com/cosmtrek/air/blob/master/air_example.toml

[build]
# Just plain old shell command. You could use `make` as well.
cmd = "templ generate && go build -o ./tmp/main ."
# Watch these filename extensions.
include_ext = ["go", "tpl", "tmpl", "html", "templ"]
# Exclude specific regular expressions.
exclude_regex = ["_templ\\.go"]